### PR TITLE
Add USBpipe PCB

### PR DESCRIPTION
**Pull request by LiPolymer**
This is the first version of my PCB :D
But it's not very nice.
Better version will coming this weekend ;) 
(note: this dedicated PCB is only recommended to experienced electronic makers. 

**DO NOT USE THIS BOARD IF YOU ARE A NEWBIE!**

### CODE REVIEW

**Comment by LiPolymer** [comment]
The PCB looks like:





Final results:

**Comment by entertheFinn** [comment]
Great color! Really enjoying the purple of the existing board. This awesome golden/orange color along with the design is really cool!

**Comment by LiPolymer** [comment]
> Great color! Really enjoying the purple of the existing board. This awesome golden/orange color along with the design is really cool!

Thank you! :D
I found I have forgotten to upload BOM list :(
I'll upload it at this weekend :)

**Comment by cecio** [comment]
Thanks a lot, it looks really cool!
Yes, if you can, please upload the BOM as well (when you have time, no rush).
I'll take a look to it in the weekend as well, then I'll merge.
Thanks for the contribution!

**Comment by LiPolymer** [comment]
Thanks for your support! ;)
The documents required for production have been uploaded. :D
I'm sorry that due to my negligence, the BOM list is in Chinese, and I will translate it into English tomorrow. :(
Thanks again! :)

**Comment by cecio** [comment]
Looks great, thanks!
Yes, if you can translate the BOM in English it would be great :-)
Thanks again

**Comment by LiPolymer** [comment]
Finally, everything is ready.
@cecio this PR can be merge now. :D
Thank you for your support! :)

**Comment by cecio** [comment]
Thanks @LiPolymer 

Everything looks perfect, only one additional request (sorry for being pedantic):
the PDF file contains some active content (Javascript) probably added automatically by the editor.  They are not harmful or malicious, but since this could trigger some security checks, I'd like to remove them. So we have two choice:
- remove the PDF entirely from the pull request
- remove the active content (if you know how to save it without)
Thanks again!

**Comment by LiPolymer** [comment]
> Thanks @LiPolymer 
> 
> Everything looks perfect, only one additional request (sorry for being pedantic):
> the PDF file contains some active content (Javascript) probably added automatically by the editor.  They are not harmful or malicious, but since this could trigger some security checks, I'd like to remove them. So we have two choice:
> - remove the PDF entirely from the pull request
> - remove the active content (if you know how to save it without)
> Thanks again!
> 

I didn't know PDF documents could contain such scripts. I'm really sorry about that. :(

This PDF file is used to display the designators,so it's not necessary to keep it a PDF file.

I don't know how to remove it from PDF, convert it into picture maybe a good solution. :)

Thanks for the heads up! :D

**Comment by LiPolymer** [comment]
@cecio Done! :D
Suspicious PDF file has been replaced! :)

**Comment by cecio** [comment]
@LiPolymer merged, thanks so much!

One thing: I realized that the link to USBpipe in the README.md is not working. I'm not sure, may be the repo is private?

**Comment by LiPolymer** [comment]
Oh, I forgot to set it to public,my fault,sorry. :(

**Comment by LiPolymer** [comment]
It's work now :D
Thank you for your remind! :)

**Pull request merged**
